server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    username: "hung"
    password: "hung07192005"
    url: "jdbc:mysql://localhost:3308/operra_identity"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
