version: '3.8'

services:
  # ===== MySQL for Identity Service =====
  mysql-identity:
    image: mysql:latest
    container_name: operra-mysql-identity
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${IDENTITY_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IDENTITY_DB}
      MYSQL_USER: ${IDENTITY_USERNAME}
      MYSQL_PASSWORD: ${IDENTITY_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql-identity-data:/var/lib/mysql
    networks:
      - operra-network

  # ===== PostgreSQL for Organization Service =====
  postgres-organization:
    image: postgres:17
    container_name: operra-postgres-organization
    restart: no
    environment:
      POSTGRES_DB: ${ORGANIZATION_DB}
      POSTGRES_USER: ${ORGANIZATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORGANIZATION_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres-organization-data:/var/lib/postgresql/data
    networks:
      - operra-network

volumes:
  mysql-identity-data:
  postgres-organization-data:

networks:
  operra-network:
    driver: bridge
