services:
  # ===== MySQL for Identity Service =====
  mysql-identity:
    image: mysql:latest
    container_name: operra-mysql-identity
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${IDENTITY_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IDENTITY_DB}
      MYSQL_USER: ${IDENTITY_USERNAME}
      MYSQL_PASSWORD: ${IDENTITY_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql-identity-data:/var/lib/mysql
    networks:
      - operra-network

  # ===== PostgreSQL for Organization Service =====
  postgres-organization:
    image: postgres:17
    container_name: operra-postgres-organization
    restart: no
    environment:
      POSTGRES_DB: ${ORGANIZATION_DB}
      POSTGRES_USER: ${ORGANIZATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORGANIZATION_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres-organization-data:/var/lib/postgresql/data
    networks:
      - operra-network
  postgres-scheduling:
    image: postgres:17
    container_name: operra-postgres-scheduling
    restart: no
    environment:
      POSTGRES_DB: ${SCHEDULING_DB}
      POSTGRES_USER: ${SCHEDULING_DB_USERNAME}
      POSTGRES_PASSWORD: ${SCHEDULING_DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - postgres-scheduling-data:/var/lib/postgresql/data
    networks:
      - operra-network
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9094:9094"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  mysql-identity-data:
  postgres-organization-data:
  postgres-scheduling-data:

networks:
  operra-network:
    driver: bridge
